LocalConfig:
  ENVIRONMENT: "local"
  DEBUG_MODE: true
  SIMULATION_NUMBER_LIMIT: null
  DATA_RETENTION_DAYS: null
  MAX_SIM_NAME_LENGTH: 20
  ABS_PATH_TO_BASE_DIRECTORY: null # If none, home directory will be used

ServerConfig:
  ENVIRONMENT: "server"
  DEBUG_MODE: false
  SIMULATION_NUMBER_LIMIT: 5
  DATA_RETENTION_DAYS: 7
  MAX_SIM_NAME_LENGTH: 20
  ABS_PATH_TO_BASE_DIRECTORY: null # If null, home directory will be used
