from aegis.Core import Plotter
import pytest, os, shutil, warnings

@pytest.fixture(scope="module")
def rec_names(request):
    """ Get record filenames generated by TestRun::test_execute."""
    listing = os.listdir(os.path.join(os.path.abspath("."),"aegis/Core/Test"))
    rec_names = []
    for filename in listing:
        if ".rec" in filename:
            rec_names.append(filename)
    return rec_names

def test_plot(rec_names):
    """Test that 'aegis plot' executes without error."""
    if not rec_names:
        s = "No records found. This tests depends on previous execution of test_4_Run::TestRun::test_execute that generates the record files needed for this test. Plotter test not run."
        warnings.warn(UserWarning(s))
    path = os.path.join(os.path.abspath("."), "aegis/Core/Test")
    for rec in rec_names:
        rec_path = os.path.join(path,rec)
        a = Plotter(rec_path)
        a.generate_figures()
        a.record["output_prefix"] = os.path.join(path,rec[:-4])
        a.save_figures()
        os.remove(rec_path)
        shutil.rmtree(a.record["output_prefix"]+"_plots")
